sudo: required

services:
    - docker

before_install:
    - docker build -t venkatdockerapp1/docker-react -f Dockerfile.dev .

# Commands need to our test script
script:
    - docker run venkatdockerapp1/docker-react npm test -- --coverage




